### ISSUE TITLE
/routes departure_time parameter

### ISSUE THREAD

**Issue by minzoovv** [2pow4/HowToGo-API#6]
질문이 있어서 issue 남깁니다. 이거 routes에서 요구하는 query param에서 departure time이 date가 아니라 시간을 말씀하는걸까요..? 어떤 형태로 제가 요청해서 보내야할지 모르겠어서 issue올립니다.

**Comment by cadenzah** [comment]
제가 처음 명세 적을 때에 날짜를 생각 안하고 적었습니다... 죄송..
응답 형태에 있는 방식처럼 날짜(`departure_date`)와 시간(`departure_time`)을 별도의 필드로 보내고, 각각이 형식은 `YYYY-MM-DD`와 `hh:mm`으로 지정하면 될 듯 합니다.
명세는 이에 맞춰서 수정할게요.

**Comment by minzoovv** [comment]
감쟈합니다
